# Generated by Django 4.1.6 on 2023-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Forwarded', 'Forwarded')], default='Pending', max_length=100),
        ),
    ]
