# Generated by Django 4.1.6 on 2023-03-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('kerberosID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Kerberos ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('kerberosID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.profile')),
                ('deptID', models.CharField(blank=True, max_length=10, null=True)),
                ('uid', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('kerberosID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.profile')),
                ('deptID', models.CharField(max_length=10)),
                ('entryNumber', models.CharField(max_length=11, unique=True)),
                ('programme', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('PostDoc', 'PostDoc'), ('MSc', 'MSc'), ('Dual Degree', 'Dual Degree')], default='B.Tech', max_length=100)),
            ],
        ),
    ]
